apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
        - name: mongos
          image: mongo:6.0
          command: ["mongos"]
          args: ["--configdb", "configReplSet/configsvr-0.mongodb:27017"]
          ports:
            - containerPort: 27017
