replicaCount: 2

image:
  repository: url-shortener-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix

redis:
  host: redis-master
  port: 6379