apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-url-shortener
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-url-shortener
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-url-shortener
    spec:
      initContainers:
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nc -z {{ .Values.redis.host }} {{ .Values.redis.port }}; do echo waiting for redis; sleep 2; done']
      containers:
      - name: url-shortener
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_URL
          value: redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3