apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-url-shortener
  namespace: {{ .Release.Namespace }}
  annotations:
    konghq.com/strip-path: "false"
spec:
  ingressClassName: kong
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $.Release.Name }}-url-shortener
            port:
              number: {{ $.Values.service.port }}
      {{- end }}
  {{- end }}