apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-url-shortener
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-url-shortener
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3000
  type: {{ .Values.service.type }}